% TOPIC: interpolation
% TITLE: Newton's divided-difference interpolation of orders 1 to 4 with centered base points
% SOURCE: Chapra Prob. 17.5
% KEYWORDS: newton's divided difference, newton interpolating polynomial, divided differences, order 1 through 4, base points centered, estimate f(4)
% PROBLEM:
% Given x = 1 2 3 5 6 and f(x) = 7 4 5.5 40 82, calculate f(4) using Newton's interpolating
% polynomials of order 1 through 4. Choose your base points to attain good accuracy (centered around
% and as close as possible to the unknown). What do your results indicate about the order of the
% polynomial used to generate the data?
% CHECK: norm(fk - [22.75 17.5 16 16]) < 1e-9
% CODE:
x = [1 2 3 5 6];
f = [7 4 5.5 40 82];
xi = 4;
fprintf('Divided-difference table (all points):\n'); disp(interp_divdiff(x, f));
fk = zeros(1, 4);
for n = 1:4
    [~, o] = sort(abs(x - xi));              % points closest to xi first
    idx = sort(o(1:n+1));
    fk(n) = interp_newton(x(idx), f(idx), xi);
    fprintf('Order %d using x = %s: f(4) = %.4f\n', n, mat2str(x(idx)), fk(n));
end
fprintf('Orders 3 and 4 agree (%.4f): the data were generated by a cubic polynomial.\n', fk(4));
